/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package webclient.fun;


import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.web.client.RestTemplateBuilder;
import org.springframework.util.StopWatch;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.reactive.function.client.WebClient;

import java.net.URI;
import java.util.List;

@Slf4j
public class App {
    public static void main(String[] args) {
        RequestMaker requestMaker = new RequestMaker(WebClient.builder().build(), new RestTemplateBuilder().build());

        StopWatch timer = new StopWatch();
        try {
            timer.start();
//            requestMaker.makePostRequest(URI.create("localhost:8000"), "ALA".getBytes());
//            requestMaker.makePostWithResttemplate(URI.create("http://localhost:8000"), "ALA".getBytes());
//            for (int i = 0; i < 100; i++) {
//                final var response = requestMaker.makeGetRequest(URI.create("localhost:8000"));
//            log.info("Response is: {}", response);
//            }
        } finally {
            timer.stop();
            log.info("Action took: {} ms", timer.getTotalTimeMillis());
        }

//        requestMaker.playWithMap();
//        requestMaker.makePostRequest(URI.create("localhost:8000"), List.of(1, 1, 2, 3, 5, 8, 13, 21, 35));
        requestMaker.makePutRequestRetrieve(URI.create("localhost:8000"));

        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
